CREATE TABLE EVENT_USERS (
    USER_ID INT(11),
    EVENT_ID INT(11),
    TYPE_ID INT(11)
);

ALTER TABLE EVENT_USERS
ADD CONSTRAINT FK_USERS_EVENT_USERS
    FOREIGN KEY(USER_ID)
    REFERENCES USERS(ID);

ALTER TABLE EVENT_USERS
ADD CONSTRAINT FK_EVENTS_EVENT_USERS
    FOREIGN KEY(EVENT_ID)
    REFERENCES EVENTS(ID);

ALTER TABLE EVENT_USERS
ADD CONSTRAINT FK_TYPE_EVENT_USERS
    FOREIGN KEY(TYPE_ID)
    REFERENCES EVENT_USER_TYPES(ID);

