CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID INT(11),
    PERMISSION_ID INT(11)
);

ALTER TABLE ROLE_PERMISSIONS
ADD CONSTRAINT FK_ROLE_ROLE_PERSMISSIONS
    FOREIGN KEY(ROLE_ID)
    REFERENCES ROLES(ID);

ALTER TABLE ROLE_PERMISSIONS
ADD CONSTRAINT FK_PERMISSION_ROLE_PERSMISSIONS
    FOREIGN KEY(PERMISSION_ID)
    REFERENCES PERMISSIONS(ID);