CREATE TABLE USER_ROLES (
    USER_ID INT(11),
    ROLE_ID INT(11)
);

ALTER TABLE USER_ROLES
ADD CONSTRAINT FK_USER_USER_ROLES
    FOREIGN KEY(USER_ID)
    REFERENCES USERS(ID);

ALTER TABLE USER_ROLES
ADD CONSTRAINT FK_ROLE_USER_ROLES
    FOREIGN KEY(ROLE_ID)
    REFERENCES ROLES(ID);