CREATE TABLE WORKGROUPS (
    ID SERIAL PRIMARY KEY,
    PARENT_ID INT(11),
    CLASSIFICATION_ID INT(11),
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(200),
    COLOR VARCHAR(6) DEFAULT '4DE3DA'
);