CREATE TABLE WORKGROUP_USERS (
    WORKGROUP_ID INT(11),
    USER_ID INT(11)
);

ALTER TABLE WORKGROUP_USERS
ADD CONSTRAINT FK_USER_WORKGROUP_USERS
    FOREIGN KEY(USER_ID)
    REFERENCES USERS(ID);

ALTER TABLE WORKGROUP_USERS
ADD CONSTRAINT FK_WORKGROUP_WORKGROUP_USERS
    FOREIGN KEY(WORKGROUP_ID)
    REFERENCES WORKGROUPS(ID);